---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kerriweb/marketplace_app
    - /bin/mkdir -p $DEPLOYPATH
     - /bin/rsync -av ./ $DEPLOYPATH \
        --exclude ".git/" \
        --exclude ".github/" \
        --exclude "node_modules/" \
        --exclude "tmp/" \
        --exclude "public/.htaccess" \
        --exclude ".htaccess"
